version: "3.9"
# 定义服务
services:
  spring-boot-demo:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        cn.netbuffer.springboot.demo.description: "spring-boot-demo webapp"
        cn.netbuffer.springboot.demo.author: "netbuffer"
        cn.netbuffer.springboot.demo.label-with-empty-value: ""
    image: netbuffer/spring-boot-demo:1.0
    container_name: spring-boot-demo-container
    hostname: spring-boot-demo
    ports:
      - "9100:9100"
    mem_swappiness: 70
    memswap_limit: -1
    oom_kill_disable: true
    deploy:
      resources:
        limits:
          memory: 4g
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: -Xms4g -Xmx8g
    restart: "no"
    volumes:
      - .env/docker-entrypoint.d/:/docker-entrypoint.d
