server:
  port: 9100
  servlet:
    session:
      timeout: 30m

req:
  mapping:
    user: user
var:
  random-int1: ${random.int}
  random-int2: ${random.int(3)}
  random-int3: ${random.int(1,10)}
  random-value: ${random.value}

logging:
  level:
    root: WARN
    org:
      springframework:
        web: INFO
    cn:
      netbuffer: DEBUG
