### bean/nameComponent
GET http://localhost:9100/bean/nameComponent

### bean/names/path
GET http://localhost:9100/bean/names/path?path=cn/netbuffer/springboot/demo

### /bean/isSingleton
GET http://localhost:9100/bean/isSingleton?bean=beanController

### /bean/isPrototype
GET http://localhost:9100/bean/isPrototype?bean=beanController

### /bean/getType
GET http://localhost:9100/bean/getType?bean=beanController

### async task with error
GET http://localhost:9100/async/error

### async sleeptask with 3 seconds
GET http://localhost:9100/async/sleeptask?sleep=3

### async dotask
GET http://localhost:9100/async/dotask?sleep=3

### /retry/test
GET http://localhost:9100/retry/test

### /param/defaultValue
GET http://localhost:9100/param/defaultValue

### /sse/sendById
GET http://localhost:9100/sse/sendById?id=uitest&message=hello

### /validator/validateUser
GET http://localhost:9100/validator/validateUser?name=netbuffer&age=32&mobile=13232233345&createTime=1672506061000

### /param/mediatype
GET http://localhost:9100/param/mediatype?value=<user><name>netbuffer</name></user>&type=xml

### /param/mediatype
GET http://localhost:9100/param/mediatype?value=hello world&type=text

### POST /param/user
POST http://localhost:9100/param/user
Content-Type: application/json

{
  "name": "your-name",
  "password": "your-name",
  "age": 30
}

### /resourceloader/staticpaths
GET http://localhost:9100/resourceloader/staticpaths

### /resourceloader/staticpaths/physicalpath
GET http://localhost:9100/resourceloader/staticpaths/physicalpath
