### /validator/getValidatorFactory
GET http://localhost:9100/validator/getValidatorFactory

### /validator/getValidator
GET http://localhost:9100/validator/getValidator

### /validator/validateUser
GET http://localhost:9100/validator/validateUser

### /validator/validateProperty
GET http://localhost:9100/validator/validateProperty

### /validator/validateValue
GET http://localhost:9100/validator/validateValue

### /validator/user
GET http://localhost:9100/validator/user?name=a

### /validator/validated/register
POST http://localhost:9100/validator/validated/register
Content-Type: application/x-www-form-urlencoded

#username=a&password=bbbbbb
username=a&password=b

### /validator/validated/calculate
GET http://localhost:9100/validator/validated/calculate?b1=102.32332&b2=323992323.1234234
